### ISSUE TITLE
Cookie message not overwriting

### ISSUE THREAD

**Issue by solidresults** [cinghie/joomla-gogo-cookie-consent#2]
I have a problem with 3 websites where the cookie message is not overwriting. 
The plugin works perfectly on other websites on the same server.

The settings are exactly the same.

**Comment by sm0rgm** [comment]
I had the same problem, when entering a custom message and submit label in the configuration it isn't displayed. Only the builtin message is showing on the frontend popup. 
I found out there is a problem if the entered message has a line break (newline/return). If I removed the line breaks and enter the text in one row without any line breaks it works for me.

**Comment by neoacevedo** [comment]
I reopen it:
Not only the message, but also the URL for the privacy policy
